source 'https://rubygems.org'

gem 'ConnectSDK'
gem 'rake'
gem 'json'
gem 'cucumber'
gem 'gherkin'
gem 'test-unit'
gem 'mockserver-client'
gem 'webmock'                                                                                                                                                                                                                                                                                                                                                                                                                           
